In [7]:
import pandas as pd
import numpy as np

data = {'A': np.random.randint(1000, 10000, 3), 
        'B': np.random.uniform(1000, 10000, 3),
        'C': ['aaa', 'bbb', '1,234']}

df = pd.DataFrame(data)

st = df.style.highlight_max()

display(st)

In [3]:
import pandas as pd
import numpy as np

data = {'A': np.random.randint(1, 10, 10), 
        'B': np.random.randint(10, 100, 10)}

df = pd.DataFrame(data)

df.style.render().split('\n')[:10]   
#render() เป็นการแสดงโค้ด HTML แล้วใช้ split() แยกบรรทัด จากนั้นเลือกเฉพาะ 10 แถวแรก

['<style  type="text/css" >',
 '</style><table id="T_e84a235c_2fb5_11ea_a109_f8597141f6ad" ><thead>    <tr>        <th class="blank level0" ></th>        <th class="col_heading level0 col0" >A</th>        <th class="col_heading level0 col1" >B</th>    </tr></thead><tbody>',
 '                <tr>',
 '                        <th id="T_e84a235c_2fb5_11ea_a109_f8597141f6adlevel0_row0" class="row_heading level0 row0" >0</th>',
 '                        <td id="T_e84a235c_2fb5_11ea_a109_f8597141f6adrow0_col0" class="data row0 col0" >9</td>',
 '                        <td id="T_e84a235c_2fb5_11ea_a109_f8597141f6adrow0_col1" class="data row0 col1" >58</td>',
 '            </tr>',
 '            <tr>',
 '                        <th id="T_e84a235c_2fb5_11ea_a109_f8597141f6adlevel0_row1" class="row_heading level0 row1" >1</th>',
 '                        <td id="T_e84a235c_2fb5_11ea_a109_f8597141f6adrow1_col0" class="data row1 col0" >8</td>']

In [51]:
import pandas as pd
import numpy as np

data = {'A': np.random.randint(1, 10, 3), 
        'B': np.random.randint(10, 100, 3)}

df = pd.DataFrame(data)

df_style = df.style.highlight_max()

print(df_style)

display(df_style)
df_style

<pandas.io.formats.style.Styler object at 0x000001AC7F953CC0>

In [4]:
import pandas as pd
import numpy as np

sr = pd.Series(np.random.randint(1, 10, 5), index=list('abcde'))
display(sr)

df = sr.to_frame()
df.style

a    9
b    4
c    6
d    6
e    8
dtype: int32

In [9]:
import pandas as pd
import numpy as np

data = {'One': np.random.randint(1, 10, 5), 
        'Two': np.random.randint(10, 100, 5),
        'Three': np.random.randint(100, 1000, 5)}

df = pd.DataFrame(data)

df.style.highlight_min()

In [8]:
import pandas as pd
import numpy as np

data = {'One': np.random.randint(1, 10, 5), 
        'Two': np.random.randint(10, 100, 5),
        'Three': np.random.randint(100, 1000, 5)}

df = pd.DataFrame(data)

df.style.highlight_max()

In [101]:
import pandas as pd
import numpy as np

data = {'A': np.random.choice([np.nan, -1, 0, 1], 5), 
        'B': np.random.choice([np.nan, 7, 11, 101, 108, 1009], 5), 
        'C': np.random.choice([np.nan, -0.25, 3.75, 1.23], 5)}

df = pd.DataFrame(data)

df.style.highlight_null()

In [4]:
import pandas as pd
import numpy as np

data = {'One': np.random.randint(1, 10, 5), 
        'Two': np.random.randint(10, 100, 5),
        'Three': np.random.randint(100, 1000, 5)}

df = pd.DataFrame(data)

display(df.style.highlight_min(color='cyan'),
        df.style.highlight_max(color='limegreen'))

In [202]:
import pandas as pd
import numpy as np

data = {'A': np.random.choice([np.nan, -1, 0, 1], 5), 
        'B': np.random.choice([np.nan, 7, 11, 101, 108, 1009], 5), 
        'C': np.random.choice([np.nan, -0.25, 3.75, 1.23], 5)}

df = pd.DataFrame(data)

df.style.highlight_null(null_color='orange')

In [19]:
import pandas as pd
import numpy as np

data = {'One': np.random.randint(1, 10, 5), 
        'Two': np.random.randint(10, 100, 5),
        'Three': np.random.randint(100, 1000, 5),
        'Four': np.random.choice([7, 11, 101, 108, 1009], 5)}

df = pd.DataFrame(data)

df.style.highlight_max(color='red', axis=0, subset=['Two', 'Three'])  #[['Two', 'Three']]

In [251]:
import pandas as pd
import numpy as np

data = {'One': np.random.choice([7, 11, 101, 108, 1009], 5), 
        'Two': np.random.choice([7, 11, 101, 108, 1009], 5),
        'Three': np.random.choice([7, 11, 101, 108, 1009], 5),
        'Four': np.random.choice([7, 11, 101, 108, 1009], 5)}

df = pd.DataFrame(data)

df.style.highlight_min(color='orange', axis=1)  #[['Two', 'Three']]

In [278]:
import pandas as pd
import numpy as np

data = {'One': np.random.choice([7, 11, 101, 108, 1009], 5), 
        'Two': np.random.choice([7, 11, 101, 108, 1009], 5),
        'Three': np.random.choice([7, 11, 101, 108, 1009], 5),
        'Four': np.random.choice([7, 11, 101, 108, 1009], 5)}

df = pd.DataFrame(data)

df[['Two', 'Three']].style.highlight_max(color='orange')

In [6]:
import pandas as pd
import numpy as np

data = {'One': np.random.choice([7, 11, 101, 108, 1009], 7), 
        'Two': np.random.choice([7, 11, 101, 108, 1009], 7),
        'Three': np.random.choice([7, 11, 101, 108, 1009], 7),
        'Four': np.random.choice([7, 11, 101, 108, 1009], 7)}

df = pd.DataFrame(data)
style1 = df.style.highlight_max(color='orange', 
                                subset=pd.IndexSlice[2:4, ['One', 'Two', 'Three']])

display(style1)

style2 = df.style.highlight_max(color='orange', 
                                subset=pd.IndexSlice[2:4])

display(style2)

In [7]:
import pandas as pd
import numpy as np

data = {'One': np.random.choice([7, 11, 101, 108, 1009], 7), 
        'Two': np.random.choice([7, 11, 101, 108, 1009], 7),
        'Three': np.random.choice([7, 11, 101, 108, 1009], 7),
        'Four': np.random.choice([7, 11, 101, 108, 1009], 7)}

df = pd.DataFrame(data)

df[2:4].style.highlight_max(color='orange')

In [8]:
import pandas as pd
import numpy as np

data = {'One': np.random.choice([7, 11, 101, 108, 1009], 5), 
        'Two': np.random.choice([7, 11, 101, 108, 1009], 5),
        'Three': np.random.choice([7, 11, 101, 108, 1009], 5),
        'Four': np.random.choice([7, 11, 101, 108, 1009], 5)}

df = pd.DataFrame(data)

df.style.highlight_min(color='orange', axis=1)

In [2]:
import pandas as pd
import numpy as np

data = {'A': np.random.randint(1, 10, 5), 
        'B': np.random.randint(10, 100, 5),
        'C': np.random.randint(100, 1000, 5)}

df1 = pd.DataFrame(data)

style1 = df1.style.highlight_max(color='cyan')
display(style1)

data2 = {'A': np.random.randint(1, 10, 5), 
         'B': np.random.randint(10, 100, 5),
         'Three': np.random.randint(100, 1000, 5)}

df2 = pd.DataFrame(data2)

style2 = df2.style
style2.use(style1.export())
style2

In [3]:
import pandas as pd
import numpy as np

data = {'A': np.random.randint(1000, 1000000, 5),
        'B': np.random.randint(1000, 1000000, 5),
        'C': np.random.randint(1000, 1000000, 5)}

df = pd.DataFrame(data)

df.style.format('{:,}')

In [4]:
import pandas as pd
import numpy as np

data = {'One': np.random.choice([12.345, 6.78910, 7.11, 108.1009, 00.0000], 5),        
        'Two': np.random.choice([-3.14159, 0.999, 1000, 1.01, .357], 5)}

df = pd.DataFrame(data)

df.style.format('{:,.2f}')

In [5]:
import pandas as pd
import numpy as np

data = {'One': np.random.randint(1000, 100000, 5),
        'Two': np.random.rand(5),
        'Three': np.random.uniform(1, 10, 5)}

df = pd.DataFrame(data)

df.style.format({'One':'{:07,}', 'Two':'{:.2%}'})

In [4]:
import pandas as pd
import numpy as np

data = {'A': np.random.randint(1000, 10000, 3), 
        'B': np.random.uniform(1000, 10000, 3),
        'C': ['aaa', 'bbb', '1,234']}

df = pd.DataFrame(data)

#st = df.style.format('{:,.2f}')
st = df.style.format('{:,.2f}', subset=['A', 'B'])

display(st)

In [2]:
import pandas as pd
import numpy as np

data = {'A': np.random.randint(1000, 10000, 3), 
        'B': np.random.uniform(1000, 10000, 3),
        'C': ['aaa', 'bbb', '1,234']}

df = pd.DataFrame(data)

st = df.style.format('{:,.2f}', subset=['A', 'B'])

display(st)

In [6]:
import pandas as pd
import numpy as np

def negative_bg(val):
    bg = '#ffc' if val < 0 else 'inherit'  #inherit คือใช้รูปแบบเดิม
    return f'background-color: {bg}'

data = {'One': np.random.randint(-5, 10, 10), 
        'Two': np.random.randint(-10, 100, 10),
        'Three': np.random.randint(-100, 1000, 10)}

df = pd.DataFrame(data)

df.style.applymap(negative_bg)

In [7]:
import pandas as pd
import numpy as np

def negative_bg(val):
    bg = 'lightyellow' if val < 0 else 'inherit'
    return f'background-color: {bg}'

def negative_color(val):
    c = 'red' if val < 0 else 'inherit'
    return f'color: {c}'    

data = {'One': np.random.randint(-5, 10, 10), 
        'Two': np.random.randint(-10, 10, 10),
        'Three': np.random.randint(-100, 100, 10)}

df = pd.DataFrame(data)

df.style.applymap(negative_bg).applymap(negative_color)

In [8]:
import pandas as pd
import numpy as np

data = {'One': np.random.randint(1, 10, 5), 
        'Two': np.random.randint(10, 100, 5),
        'Three': np.random.randint(100, 1000, 5)}

df = pd.DataFrame(data)

df.style.set_properties(**{'background-color': 'black',
                           'color': 'lawngreen',                          
                           'border-style': 'solid',
                           'border-width': 'thin',
                           'border-color': 'lightgray',
                           'font-size': 'larger', 
                           'font-weight': 'bold',
                           'text-align': 'center'})

In [9]:
import pandas as pd
import numpy as np

data = {'One': np.random.randint(1, 10, 5), 
        'Two': np.random.randint(10, 100, 5),
        'Three': np.random.randint(100, 1000, 5)}

df = pd.DataFrame(data)
df.style.set_table_styles([
        {'selector': 'thead', 
         'props': [('border-bottom', 'none'), 
                   ('background-color', 'navy'), 
                   ('color', 'aqua'), ('font-size', '1.7rem')]},
    
        {'selector': 'tbody tr:hover', 
         'props': [('background-color', 'yellow !important')]},
    
        {'selector': 'tbody tr:nth-child(odd)', 
         'props': [('background-color', 'lightblue')]},
    
        {'selector': 'tbody tr:nth-child(even)', 
         'props': [('background-color', 'lightgreen')]},
    
        {'selector': 'tbody tr', 
         'props': [('border-top', 'solid 1px white')]}, 
    
        {'selector': 'td', 
         'props': [('padding', '10px'), ('font-size', '1.5rem')]}  
     ])

In [ ]:
import pandas as pd
import numpy as np

def negative_bg(val):
    bg = 'yellow' if val < 0 else 'white'
    return f'background-color: {bg}'

def negative_color(val):
    c = 'red' if val < 0 else 'black'
    return f'color: {c}'    

data = {'One': np.random.randint(-5, 10, 10), 
        'Two': np.random.randint(-10, 10, 10),
        'Three': np.random.randint(-100, 100, 10)}

df = pd.DataFrame(data)

df.style \
    .applymap(negative_bg) \
    .applymap(negative_color) \
    .to_excel('c:\py\dsc\styling.xlsx')

In [10]:
import pandas as pd
import numpy as np

data = {'P1': np.random.randint(10, 100, 7),
        'P2': np.random.randint(10, 100, 7), 
        'P3': np.random.randint(10, 100, 7)}

df = pd.DataFrame(data, index=np.arange(1, 8))

df.style.set_caption('ยอดขายสินค้า 3 ชนิด ในรอบ 7 วัน').highlight_max()

In [11]:
import pandas as pd
import numpy as np

data = {'One': np.random.randint(10, 100, 5),
        'Two': np.random.randint(10, 100, 5), 
        'Three': np.random.randint(10, 100, 5),
        'Four': np.random.randint(10, 100, 5)}

df = pd.DataFrame(data)

display(df.style.hide_index())
df.style.hide_columns(['One', 'Three'])

In [12]:
import pandas as pd
import numpy as np
import seaborn as sns

data = {'One': np.random.randint(100, 1000, 5),
        'Two': np.random.randint(100, 1000, 5), 
        'Three': np.random.randint(100, 1000, 5),
        'Four': np.random.randint(100, 1000, 5)}

df = pd.DataFrame(data)
cm = sns.light_palette('lightblue', as_cmap=True)

df.style.background_gradient(cmap=cm)
#df.style.background_gradient(cmap='viridis', low=0.5, high=0)

In [13]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', 10)
pd.set_option('max_columns', 2)
pd.set_option('precision', 2)

data = {'One': np.random.uniform(10, 100, 20), 
        'Two': np.random.uniform(10, 100, 20),
        'Three': np.random.uniform(10, 100, 20),
        'Four': np.random.uniform(10, 100, 20),
        'Five': np.random.uniform(10, 100, 20)}

df = pd.DataFrame(data)

df

      One  ...   Five
0   51.23  ...  12.33
1   90.41  ...  42.72
2   43.51  ...  76.13
3   85.11  ...  13.94
4   19.69  ...  43.28
..    ...  ...    ...
15  14.60  ...  49.62
16  16.90  ...  43.47
17  50.92  ...  23.82
18  84.89  ...  74.08
19  36.89  ...  90.06

[20 rows x 5 columns]